name: Docs Build

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    docs-build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.12
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
            cache: 'pip'       
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -e '.[doc]'

        - name: Build Docs
          run: |
            sphinx-build -b html docs/ docs/build/

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: docs-build
            path: docs/build/
