# This workflow will install Python dependencies and run self-tests.
# ref: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # actions/setup-python@v5 has built-in functionality for caching and restoring dependencies. 
    - name: Install Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
      
    - name: Self-test
      run: |
        pytest --pyargs scpdt -v -s

    - name: Self-test CLI
      run: |
        python -m scpdt scpdt/tests/finder_cases.py -vv


    
